version: '3.9'

networks:
  test-network:
    driver: bridge

services:
  rangiffler-all-db:
    container_name: rangiffler-all-db
    image: postgres:15.1
    environment:
      - POSTGRES_MULTIPLE_DATABASES="rangiffler-auth","rangiffler-userdata","rangiffler-geo","rangiffler-photo"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 3s
      timeout: 3s
      retries: 5
    expose:
      - "5432"
    networks:
      - test-network
    dns_search: .

  rangiffler-auth:
    container_name: rangiffler-auth
    image: miron9/rangiffler-auth:latest
    ports:
      - "9000:9000"
    healthcheck:
      test: "wget --spider http://localhost:9000/actuator/health || exit 1"
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      rangiffler-all-db:
        condition: service_healthy
    networks:
      - test-network
    dns_search: .

  rangiffler-currency:
    container_name: rangiffler-geo
    image: miron9/rangiffler-geo:latest
    expose:
      - "8091"
      - "8092"
    depends_on:
      rangiffler-all-db:
        condition: service_healthy
    networks:
      - test-network
    dns_search: .

  rangiffler-gateway:
    container_name: rangiffler-gateway
    image: miron9/rangiffler-gateway:latest
    ports:
      - "8090:8090"
    depends_on:
      rangiffler-auth:
        condition: service_started
    networks:
      - test-network
    dns_search: .

  rangiffler-photo:
    container_name: rangiffler-photo
    image: miron9/rangiffler-photo:latest
    expose:
      - "8093"
      - "8094"
    depends_on:
      rangiffler-all-db:
        condition: service_healthy
    networks:
      - test-network
    dns_search: .

  rangiffler-userdata:
    container_name: rangiffler-userdata
    image: miron9/rangiffler-userdata:latest
    expose:
      - "8089"
    depends_on:
      rangiffler-all-db:
        condition: service_healthy
    networks:
      - test-network
    dns_search: .

  rangiffler-frontend:
    container_name: rangiffler-frontend
    image: miron9/rangiffler-frontend-test:latest
    ports:
      - "80:80"
    depends_on:
      rangiffler-gateway:
        condition: service_started
    networks:
      - test-network
    dns_search: .

  selenoid:
    container_name: selenoid
    image: aerokube/selenoid:1.10.10
    volumes:
      - ./selenoid:/etc/selenoid
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: [ "-conf", "/etc/selenoid/browsers.json", "-limit", "3", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "rangiffler_test-network" ]
    ports:
      - "4444:4444"
    networks:
      - test-network
    dns_search: .

  selenoid-ui:
    container_name: selenoid-ui
    image: aerokube/selenoid-ui:1.10.9
    depends_on:
      - selenoid
    restart: unless-stopped
    ports:
      - "9090:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
    networks:
      - test-network
    dns_search: .

  rangiffler-e-2-e:
    container_name: rangiffler-e-2-e
    image: miron9/rangiffler-e-2-e-tests
    depends_on:
      rangiffler-frontend:
        condition: service_started
    networks:
      - test-network
    dns_search: .

  allure:
    container_name: allure
    image: frankescobar/allure-docker-service
    depends_on:
      - rangiffler-e-2-e
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 3
      KEEP_HISTORY: 0
    ports:
      - "5050:5050"
    networks:
      - test-network
    dns_search: .
